import 'package:flutter/material.dart';

/// The official Reebaplus logo, picked for the current theme.
///
/// The dark artwork (light-grey "R", white wordmark) is used on dark themes
/// and the light artwork (dark "R", black wordmark) on light themes. Both
/// have transparent backgrounds, so they sit on any page background.
///
/// [lockup] adds the "Reebaplus" wordmark under the ring mark; leave it off
/// where the screen already prints the name next to the logo.
///
/// [brightness] overrides the theme — for screens drawn before the app theme
/// is known (e.g. the startup splash, which follows the device setting).
///
/// Assets are generated by `tool/generate_brand_assets.dart` from the
/// designer's files in `assets/branding/`. Never reference them directly.
class ReebaplusLogo extends StatelessWidget {
  const ReebaplusLogo({
    super.key,
    required this.height,
    this.lockup = false,
    this.brightness,
  });

  final double height;
  final bool lockup;
  final Brightness? brightness;

  static String assetFor({
    required bool lockup,
    required Brightness brightness,
  }) {
    final kind = lockup ? 'lockup' : 'mark';
    final theme = brightness == Brightness.dark ? 'dark' : 'light';
    return 'assets/images/brand/reebaplus_${kind}_$theme.png';
  }

  @override
  Widget build(BuildContext context) {
    final b = brightness ?? Theme.of(context).brightness;
    return Image.asset(
      assetFor(lockup: lockup, brightness: b),
      height: height,
      fit: BoxFit.contain,
      filterQuality: FilterQuality.medium,
      semanticLabel: 'Reebaplus',
      errorBuilder: (context, _, _) => SizedBox(height: height, width: height),
    );
  }
}
